name: Preprod

on:
  push:
    branches-ignore: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: PATH
        run: |
          pwd
          ls -lha 

      - name: CLONE
        run: |
           cd /home/runner
           mkdir vaxzk
           cd vaxzk
           git clone --depth 1 https://.:${{ secrets.API_TOKEN_GITHUB }}@github.com/sociapbr/vaxzk-homolog.git .

      - name: INSTALL
        run: |
           npm install --force

      - name: COMPACT
        run: |
           curl --proto '=https' --tlsv1.2 -LsSf https://github.com/midnightntwrk/compact/releases/latest/download/compact-installer.sh | sh
           compact update
           compact compile contract/vaxzk.compact contract/managed
           mkdir -p public/keys public/zkir
           cp -r contract/managed/keys/* public/keys/
           cp -r contract/managed/zkir/* public/zkir/

      - name: TEST
        run: |
           npm run test

      - name: DEPLOY
        run: |
           npm run build
           rm -rf /home/runner/vaxzk/*           
           cp -r contract/managed dist/assets/
           cp -r dist/* /home/runner/vaxzk/

      - name: SAVE
        run: |
           cd /home/runner/vaxzk/
           git config --global user.email "marco@sociap.com.br"
           git config --global user.name "Marco Santos"
           git add .
           git commit -m "Automatic publish from vaxzk"
           git push
